name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Git tag if not exists
        run: |
          if git rev-parse "${{ github.event.inputs.tag }}" >/dev/null 2>&1; then
            echo "The tag ${{ github.event.inputs.tag }} already exists."
          else
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git tag "${{ github.event.inputs.tag }}"
            git push origin "${{ github.event.inputs.tag }}"
          fi

  build:
    needs: create_tag
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.28"

      - name: Install dependencies
        run: bun install

      - name: Build binary
        run: bun run build:bin

      - name: Rename artifact for Linux
        if: runner.os == 'Linux'
        run: mv dist/helix-rich-lsp dist/helix-rich-lsp-linux-x64

      - name: Rename artifact for macOS
        if: runner.os == 'macOS'
        run: mv dist/helix-rich-lsp dist/helix-rich-lsp-macos-x64

      - name: Upload artifact for Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: helix-rich-lsp-linux-x64
          path: dist/helix-rich-lsp-linux-x64

      - name: Upload artifact for macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: helix-rich-lsp-macos-x64
          path: dist/helix-rich-lsp-macos-x64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: helix-rich-lsp-linux-x64

      - name: Download artifact (macOS)
        uses: actions/download-artifact@v4
        with:
          name: helix-rich-lsp-macos-x64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false

      - name: Upload release asset (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: helix-rich-lsp-linux-x64
          asset_name: helix-rich-lsp-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload release asset (macOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: helix-rich-lsp-macos-x64
          asset_name: helix-rich-lsp-macos-x64
          asset_content_type: application/octet-stream
